CREATE OR REPLACE FUNCTION timestamps_gen()
    RETURNS trigger
    LANGUAGE plpgsql
AS $BODY$
BEGIN
    if (TG_OP = 'INSERT') then
        if (new.inserted_at is null) then
            new.inserted_at = (CURRENT_TIMESTAMP at time zone 'utc');
        END if;
    end if;

    if (TG_OP = 'UPDATE') then
        new.updated_at = (CURRENT_TIMESTAMP at time zone 'utc');
    end if;

    RETURN NEW;
END;
$BODY$;

CREATE TABLE ra_migrations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number integer not null,
    name varchar(200) not null,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc')
);
