DROP TABLE IF EXISTS ra_job_logs CASCADE;
DROP TABLE IF EXISTS ra_job_details CASCADE;
DROP TABLE IF EXISTS ra_jobs CASCADE;
DROP TYPE IF EXISTS ra_job_type CASCADE;

DROP TABLE IF EXISTS ra_users CASCADE;
DROP TABLE IF EXISTS ra_nodes CASCADE;
DROP TYPE IF EXISTS ra_node_type CASCADE;
