CREATE TABLE ra_user_passphrases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint not null,
    passphrase varchar(192) not null,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc')
);

CREATE INDEX ra_user_passphrases_user_id_index ON ra_user_passphrases USING btree(user_id);
CREATE UNIQUE INDEX ra_user_passphrases_passphrase_unique_index ON ra_user_passphrases USING btree(passphrase);
