CREATE TYPE ra_process_type AS ENUM ('insert', 'update', 'distributing');

CREATE TABLE IF NOT EXISTS ra_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id bigint not null,
    parent_id bigint null,
    dir varchar(200) not null,
    file varchar(200) not null,
    type ra_node_type default 'worker',
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc'),

    CONSTRAINT fk_ra_files_node_id FOREIGN KEY (node_id)
        REFERENCES ra_nodes(id) ON UPDATE CASCADE ON DELETE cascade,
    CONSTRAINT fk_ra_files_parent_id FOREIGN KEY (parent_id)
        REFERENCES ra_files(id) ON UPDATE CASCADE ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS ra_file_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id bigint not null,
    file_id bigint not null,
    source_user_id bigint null,
    type ra_process_type default 'insert',
    data jsonb null,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc'),

    CONSTRAINT fk_ra_file_logs_node_id FOREIGN KEY (node_id)
        REFERENCES ra_nodes(id) ON UPDATE CASCADE ON DELETE cascade,
    CONSTRAINT fk_ra_file_logs_upload_id FOREIGN KEY (file_id)
        REFERENCES ra_files(id) ON UPDATE CASCADE ON DELETE SET NULL ,
    CONSTRAINT fk_ra_file_logs_source_user_id FOREIGN KEY (source_user_id)
        REFERENCES ra_users(id) ON UPDATE CASCADE ON DELETE SET NULL
);
